---
- name: Add RPM validation key
  become: true
  rpm_key:
    key: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    validate_certs: true
- name: Install Kibana
  become: true
  yum:
    name: "/tmp/kibana-{{ kibana_version }}-x86_64.rpm"
    state: present
  notify: restart Kibana
