FROM debian:stretch

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get install -y --no-install-recommends python3 sudo bash ca-certificates iproute2 python3-apt aptitude apt-utils ansible gcc git python3-click python3-dev python3-pip python3-setuptools python3-virtualenv python3-toml libssl-dev rsync systemd && apt-get clean && rm -rf /var/lib/apt/lists/*
