# Molecule managed
 
{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}
ENV container=docker
 
{# Initial Package Installs and Container Prep #}
{% if item.image.split(':', 1)[0] in ["ubuntu"] %}
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
     locales software-properties-common rsyslog systemd systemd-cron sudo \
     iproute2
RUN sed -i 's/^\($ModLoad imklog\)/#\1/' /etc/rsyslog.conf
{% elif item.image.split(':', 1)[0] in ["debian"] %}
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       sudo systemd systemd-sysv \
       build-essential wget
{% elif item.image.split(':', 1)[0] in ["centos"] %}
{% if item.image in ["centos:7"] %}
RUN yum makecache fast && yum -y install deltarpm \
{% elif item.image in ["centos:8"] %}
RUN yum makecache --timer \
{% endif %}
    && yum -y install epel-release \
    && yum -y update \
    && yum -y install sudo which
{% endif %}
 
 
{# Install of Python2 #}
{% if item.image in ["ubuntu:16.04"] %}
RUN apt-get update \
    && apt-get install -y --no-install-recommends python-setuptools wget \
    && wget https://bootstrap.pypa.io/get-pip.py \
    && python get-pip.py
{% elif item.image in ["debian:9"] %}
RUN apt-get update \
    && apt-get install -y --no-install-recommends libffi-dev libssl-dev \
       python-pip python-dev python-setuptools python-wheel
{% elif item.image in ["centos:7"] %}
RUN yum -y install python-pip
{% endif %}
 
{# Install of Python3 #}
{% if item.image in ["ubuntu:18.04", "ubuntu:20.04", "debian:10"] %}
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       apt-utils python3-setuptools python3-pip
{% endif %}
{% if item.image in ["centos:8"] %}
RUN yum -y install hostname python3 python3-pip
{% endif %}
 
{% if item.image in ["centos:7", "centos:8", "debian:9", "debian:10"] %}
VOLUME ["/sys/fs/cgroup"]
{% elif item.image in ["ubuntu:16.04", "ubuntu:18.04", "ubuntu:20.04"] %}
VOLUME ["/sys/fs/cgroup", "/tmp", "/run"]
{% endif %}
{% if item.image in ["centos:7", "centos:8"] %}
ENTRYPOINT ["/usr/sbin/init"]
{% elif item.image in ["ubuntu:16.04", "ubuntu:18.04", "ubuntu:20.04", "debian:9", "debian:10"] %}
ENTRYPOINT ["/lib/systemd/systemd"]
{% endif %}
