---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: kibana
  gather_facts: false
  tasks:
  - name: Check conf file
    stat:
      path: /etc/kibana/kibana.yml
    check_mode: true
    register: stat_result
    failed_when: not stat_result.stat.exists
  - name: Check conf is configured
    lineinfile:
      path: /etc/kibana/kibana.yml
      line: 'server.host: "0.0.0.0"'
      state: present
    check_mode: true
    register: conf
    failed_when: (conf is changed) or (conf is failed)
  - name: Check Kibana service
    service_facts:
    register: services_state
    failed_when: services_state['ansible_facts']['services']['kibana.service']['state'] != 'running'
  - name: Check Kibana web interface
    uri:
      url: "http://localhost:5601"
    register: result
    until: result is not failed
    retries: 5
    delay: 15
